# Generated by Django 4.2.26 on 2025-11-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_blockchainreceipt_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainreceipt',
            name='action',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='blockchainreceipt',
            name='signed_payload',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='blockchainreceipt',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='blockchainreceipt',
            name='wallet_public_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blockchainreceipt',
            name='wallet_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
