# Generated by Django 4.2.26 on 2025-11-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_blockchainreceipt_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainreceipt',
            name='metadata_label',
            field=models.CharField(default='674', max_length=16),
        ),
    ]
