# Generated by Django 4.2.26 on 2025-11-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_blockchainreceipt_metadata_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockchainreceipt',
            options={},
        ),
        migrations.AddField(
            model_name='blockchainreceipt',
            name='network',
            field=models.CharField(default='testnet', max_length=32),
        ),
        migrations.AlterField(
            model_name='blockchainreceipt',
            name='hash_value',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='blockchainreceipt',
            name='metadata_label',
            field=models.CharField(default='721', max_length=32),
        ),
        migrations.AlterField(
            model_name='blockchainreceipt',
            name='transaction_hash',
            field=models.CharField(max_length=128),
        ),
    ]
